[package]
name = "patisson-bybit-sdk"
version = "0.2.3"
edition = "2024"
authors = ["Yurii Musolov <yurii.musolov@gmail.com>"]
description = "Unofficial Rust SDK for the Bybit exchange API"
keywords = ["bybit", "sdk", "crypto", "trading", "cryptocurrency"]
categories = ["api-bindings", "cryptography::cryptocurrencies"]
documentation = "https://docs.rs/crate/patisson-bybit-sdk"
repository = "https://github.com/yurii-musolov/patisson-bybit-sdk"
license = "MIT"
license-file = "LICENSE"
readme = "README.md"
include = [
  "/src/**/*",
  "/examples/**/*",
  "/Cargo.toml",
  "/README.md",
  "/LICENSE",
]

[lib]
name = "bybit"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.102"
futures = "0.3.32"
futures-util = { version = "0.3.32", default-features = false, features = [
  "sink",
  "std",
] }
hex = "0.4.3"
hmac = "0.13.0"
reqwest = { version = "0.13.4", features = ["json", "query"] }
rust_decimal = { version = "1.42.1", features = [
  "std",
  "macros",
  "serde-str",
  "serde-with-str",
] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
serde_path_to_error = "0.1.20"
serde_repr = "0.1.20"
serde_urlencoded = "0.7.1"
serde-aux = "4.7"
sha2 = "0.11.0"
thiserror = "2.0.18"
tokio = { version = "1.52.3", features = ["full"] }
tokio-tungstenite = { version = "0.29.0", features = ["native-tls"] }
tokio-util = "0.7.18"
tracing = "0.1.44"
tungstenite = "0.29.0"
url = "2.5.8"

[dev-dependencies]
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
